### ISSUE TITLE
Interview with @weihanglo

### ISSUE THREAD

**Issue by Folyd** [RustMagazine/rustmagazine#10]
Thanks, @weihanglo for accepting my interview invitation. @weihanglo is my friend (we met each other in 2019) and a member of [the cargo team](https://www.rust-lang.org/governance/teams/dev-tools#Cargo%20team). We'll have a talk soon, here is the outline.

# Outline

- Introduce yourself and share a bit about your background with Rust. When did you start learning Rust and what inspired you to do so?
- Can you share the story of how you joined the Cargo team? What was the process like and what attracted you to the opportunity?
- How does the Cargo team work on a day-to-day basis? Do you have weekly meetings or a specific workflow that you follow?
- As a member of the Cargo team for nearly a year, can you share some of the tasks that you have worked on and the accomplishments that you are most proud of?
- How do you balance your daily job with working on Cargo in your free time? Do you have any tips for others who are interested in contributing to open source projects while also managing a full-time job or other responsibilities?
- What do you think are the biggest challenges facing the Cargo team right now? How do you plan to tackle these challenges in the future?
- Does the Cargo team have any specific plans or goals for the coming year or two? Can you give us a sneak peek into what we can expect from Cargo in the near future?
- In addition to your work on Cargo, do you contribute to any other open source projects, either as an individual or as part of an organization? Can you share a little bit about some of these other projects and what you enjoy?

> Improved by ChatGPT

**Comment by LCrossman** [comment]
+1``
