### ISSUE TITLE
License notice for the articles

### ISSUE THREAD

**Issue by giuseppe998e** [RustMagazine/rustmagazine#13]
I believe it is useful for those who publish and for those who would like to use/cite the contents of the magazine that the type of license the articles are subject to (eg. _Creative Commons_) is explicated.

I was thinking of "_CC BY-SA_" to leave freedom for those who use the content to do (almost) what they want with it being an "open" magazine, however, this is just my first thought and I guess it needs to be debated anyway.

**Comment by Folyd** [comment]
Thanks for the suggestion. We indeed need to add license notice. Cc. @LCrossman

**Comment by LCrossman** [comment]
So this sounds like a sensible and good idea.  The only thing I could see
against it is if someone in a particular article wants a more restrictive
term if they are providing software and wouldn't want to be a part of the
zine unless there was for example, a CC-BY-ND ?  But in that case I guess
you could have the descriptive article and just link to their github with
their software license on.
Any other experiences or thoughts?
L

**Comment by giuseppe998e** [comment]
Then it might work better to have a variable in the markdown source header where each author could enter the license they want.

**Comment by Nugine** [comment]
I would like to use/cite some parts from Rust Magazine in my articles. 
Currently the license is [MIT](https://github.com/RustMagazine/rustmagazine/blob/ea4212f08d70365d7cab29971b0ff4cc0946d0a4/LICENSE). I will reserve the original link and the author name, is it enough?
