### ISSUE TITLE
Some 404

### ISSUE THREAD

**Issue by xxchan** [RustMagazine/rustmagazine#71]
https://rustmagazine.org/feed.xml
<img width="279" alt="image" src="https://user-images.githubusercontent.com/37948597/223766065-0f50d663-d785-43d6-8ea0-759f30d249a4.png">

https://rustmagazine.org/issue-2/write-a-sql-optimizer-using-egg

<img width="485" alt="image" src="https://user-images.githubusercontent.com/37948597/223766184-0c4e3ee7-e36e-46a6-bd34-5f0a566ce0b8.png">

**Comment by Folyd** [comment]
Fixed. Thanks for the feedback. 👍
