### ISSUE TITLE
Backtick inline code is hard to read

### ISSUE THREAD

**Issue by Boshen** [RustMagazine/rustmagazine#82]
![image](https://user-images.githubusercontent.com/1430279/230257534-4589f947-ca3a-4a58-b6b6-2890c471d56e.png)

See image above, it currently displays a backtick with bold text, I think we want monofont with gray background instead.

**Comment by Folyd** [comment]
Thanks for the feedback. https://github.com/zineland/zine/commit/71e9626c26e29c969e279dabf9d374d34c584a61 fixed it.
<img width="807" alt="image" src="https://user-images.githubusercontent.com/3369694/232061709-8a34913c-d300-427f-950a-ab6c5e1733ab.png">
